#pragma once

#define MOUSEKEY_INERTIA

#define TAPPING_TERM 200

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MAX_SPEED 24
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_FRICTION 80

#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 40
#define MOUSEKEY_WHEEL_MAX_SPEED 12
#define MOUSEKEY_WHEEL_TIME_TO_MAX 12

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#undef BOOTMAGIC_ROW
#define BOOTMAGIC_ROW 0
#undef BOOTMAGIC_COLUMN
#define BOOTMAGIC_COLUMN 0

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 9
