name: Monthly QMK Rebase & Build

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  issues: write

jobs:
  rebase_and_build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    env:
      BRANCH: nymphium

    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ env.BRANCH }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch upstream and rebase
        id: rebase
        continue-on-error: true
        run: |
          git remote add upstream https://github.com/qmk/qmk_firmware.git
          git fetch upstream master
          git rebase upstream/master 2>&1 | tee rebase.log

      - name: Create Issue on rebase failure
        if: steps.rebase.outcome != 'success'
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GGITHUB_TOKEN }}
          title: "🚨 Monthly QMK rebase failed for ${{ env.BRANCH }}"
          content-filepath: ./rebase.log

      - if: steps.rebase.outcome != 'success'
        run: exit 0

      - name: Set up QMK CLI
        run: |
          python3 -m pip install qmk
          qmk setup --yes

      - name: Build keymap
        id: build
        continue-on-error: true
        run: |
          for rule in zsa/moonlander:nymphium crkbd/rev4_1/standard:nymphium; do
            make "$rule"
          done

      - name: Create Issue on build failure
        if: steps.build.outcome != 'success'
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "🚨 Monthly QMK build failed"
          content: |
            QMK monthly rebase and build failed!
            Please check the latest upstream changes.

            ### Build log:
            ```
            ${{ steps.build.outputs.stderr }}
            ```

      - name: Rebase and push upstream changes
        if: steps.build.outcome == 'success'
        run: git push --force-with-lease origin ${{ env.BRANCH }}
